version: '3'

services:
  expulsabot:
    build: ./
    image: atareao/expulsabot:v2.0
    container_name: expulsabot
    init: true
    restart: unless-stopped
    volumes:
      - ./database:/app/database
    env_file:
      - expulsabot.env
